# Generated by Django 3.2.18 on 2023-07-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20, unique=True)),
                ('IPv4', models.CharField(max_length=20)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20, unique=True)),
                ('protocol', models.CharField(max_length=20, null=True)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('path', models.CharField(blank=True, default=None, max_length=255)),
                ('correct_http_response_code', models.IntegerField(null=True)),
                ('correct_http_response', models.CharField(max_length=100, null=True)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=20, unique=True)),
                ('device_type', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=50, null=True)),
                ('hostname', models.CharField(max_length=20, null=True)),
                ('host', models.CharField(max_length=100, null=True)),
                ('CPU_cores', models.IntegerField(default=None)),
                ('RAM', models.CharField(max_length=20, null=True)),
                ('HDD', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('key_file', models.CharField(max_length=255, null=True)),
                ('timeout', models.IntegerField()),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.CharField(blank=True, max_length=255)),
                ('uptime', models.CharField(max_length=20, null=True)),
                ('cpu_load_1', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('cpu_load_5', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('cpu_load_15', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('mem_used', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('disk_usage', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.systems')),
            ],
        ),
        migrations.CreateModel(
            name='SystemsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=None)),
                ('pid', models.IntegerField(blank=True, default=None)),
                ('realtime_timestamp', models.IntegerField(blank=True, default=None)),
                ('message', models.TextField(blank=True, default=None)),
                ('hostname', models.CharField(max_length=40, null=True)),
                ('code_func', models.CharField(max_length=255, null=True)),
                ('cmdline', models.CharField(max_length=255, null=True)),
                ('ignored', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.systems')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.CharField(blank=True, max_length=255)),
                ('availability', models.BooleanField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.services')),
            ],
        ),
        migrations.CreateModel(
            name='InternetAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.CharField(blank=True, max_length=255)),
                ('availability', models.BooleanField()),
                ('destination', models.CharField(max_length=20, null=True)),
                ('packet_transmit', models.IntegerField()),
                ('packet_receive', models.IntegerField()),
                ('packet_loss_count', models.IntegerField()),
                ('packet_loss_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('rtt_min', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('rtt_avg', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('rtt_max', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('rtt_mdev', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('packet_duplicate_count', models.IntegerField(null=True)),
                ('packet_duplicate_rate', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('iservice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.iservices')),
            ],
        ),
    ]
