# Generated by Django 3.2.18 on 2023-07-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemslogs',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemslogs',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
