# Generated by Django 3.2.18 on 2023-07-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systems',
            name='CPU_cores',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
