# Generated by Django 3.2.18 on 2023-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_systems_cpu_cores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemslogs',
            name='pid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='systemslogs',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
